name: Build and Deploy

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: docker
    container:
      image: docker:cli
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout
        run: |
          git clone --depth 1 http://forgejo:3000/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Build Docker Image
        run: |
          docker build -t localhost:5000/sceneforged:latest .
          docker tag localhost:5000/sceneforged:latest localhost:5000/sceneforged:${{ github.sha }}

      - name: Push to Registry
        run: |
          docker push localhost:5000/sceneforged:latest
          docker push localhost:5000/sceneforged:${{ github.sha }}

      - name: Deploy
        run: |
          # Stop and remove existing container
          docker stop sceneforged || true
          docker rm sceneforged || true
          # Start new container with same config as compose
          docker run -d \
            --name sceneforged \
            --restart unless-stopped \
            --network media \
            -p 8080:8080 \
            -e TZ=Europe/London \
            -e RUST_LOG=info \
            -v /opt/docker-config/sceneforged:/config:rw \
            -v /mnt/data/Public/Media/Movies/Movies:/media/movies:rw \
            -v /mnt/data/Public/Media/Movies/Movies-Theater:/media/movies-theater:rw \
            -v /mnt/data/Public/Media/Movies/Re-Cuts:/media/recuts:rw \
            -v /mnt/data/Public/Media/TV:/media/tv:rw \
            -v /mnt/data/downloads/synced:/downloads:rw \
            localhost:5000/sceneforged:latest
