name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: docker
    container:
      image: docker:cli
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout
        run: |
          git clone --depth 1 http://forgejo:3000/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Build Docker Image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --build-arg COMMIT_SHA=${{ github.sha }} \
            -t ike:3002/dallas/sceneforged:latest .
          docker tag ike:3002/dallas/sceneforged:latest ike:3002/dallas/sceneforged:${{ github.sha }}

      - name: Login to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ike:3002 -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Push to Registry
        run: |
          docker push ike:3002/dallas/sceneforged:latest
          docker push ike:3002/dallas/sceneforged:${{ github.sha }}

      - name: Deploy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /opt/stacks/sceneforged:/stack \
            docker:cli \
            docker compose -f /stack/compose.yaml up -d --force-recreate --pull always
