/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/arrs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Arr integrations. */
        get: operations["get_arrs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arrs/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Arr integration connection. */
        post: operations["test_arr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API health status. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job history. */
        get: operations["get_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all items with filtering. */
        get: operations["list_items_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an item by ID. */
        get: operations["get_item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get children of an item. */
        get: operations["get_children"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get media files for an item. */
        get: operations["get_item_files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get similar items (placeholder - returns items from same genre/library). */
        get: operations["get_similar_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active jobs. */
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a new job for processing. */
        post: operations["submit_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific job by ID. */
        get: operations["get_job"];
        put?: never;
        post?: never;
        /** Delete a job. */
        delete: operations["delete_job"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed job. */
        post: operations["retry_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all libraries. */
        get: operations["list_libraries"];
        put?: never;
        /** Create a new library. */
        post: operations["create_library"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{library_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a library by ID. */
        get: operations["get_library"];
        put?: never;
        post?: never;
        /** Delete a library. */
        delete: operations["delete_library"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{library_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get items in a library. */
        get: operations["get_library_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{library_id}/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recently added items in a library. */
        get: operations["get_recent_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{library_id}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan a library for new media files. */
        post: operations["scan_library"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current job queue. */
        get: operations["get_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all processing rules. */
        get: operations["get_rules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search items. */
        get: operations["search_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get processing statistics. */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status of external tools. */
        get: operations["get_tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Processing action. */
        Action: {
            /** @description Convert Dolby Vision profile */
            DvConvert: {
                /** Format: int32 */
                target_profile: number;
            };
        } | {
            /** @description Remux to different container */
            Remux: {
                container: string;
                keep_original: boolean;
            };
        } | {
            /** @description Add compatibility audio track */
            AddCompatAudio: {
                source_codec: string;
                target_codec: string;
            };
        } | {
            /** @description Strip tracks by type or language */
            StripTracks: {
                languages: string[];
                track_types: string[];
            };
        } | {
            /** @description Execute external command */
            Exec: {
                args: string[];
                command: string;
            };
        };
        /** @description Arr integration status. */
        ArrStatus: {
            /** @description Whether the integration is enabled */
            enabled: boolean;
            /** @description Integration name */
            name: string;
            /** @description Connection status */
            status: string;
            /** @description Integration type (radarr/sonarr) */
            type: string;
            /** @description Server URL */
            url: string;
        };
        /**
         * @description Arr integration type.
         * @enum {string}
         */
        ArrType: "radarr" | "sonarr";
        /** @description Request to create a new library. */
        CreateLibraryRequest: {
            /** @description Type of media in this library (movie, series) */
            media_type: string;
            /** @description Library name */
            name: string;
            /** @description Paths to scan for media files */
            paths: string[];
        };
        /** @description Health check response. */
        HealthResponse: {
            /** @description Processing statistics */
            stats: components["schemas"]["HealthStats"];
            /** @description Service status */
            status: string;
            /** @description Application version */
            version: string;
        };
        /** @description Health statistics. */
        HealthStats: {
            /**
             * Format: float
             * @description Success rate percentage
             */
            success_rate: number;
            /**
             * Format: int64
             * @description Total jobs processed
             */
            total_processed: number;
        };
        /** @description Media item information. */
        ItemResponse: {
            /**
             * Format: double
             * @description Community rating
             */
            community_rating?: number | null;
            /** @description When the item was added */
            date_created: string;
            /** @description Dolby Vision profile */
            dolby_vision_profile?: string | null;
            /** @description Genres */
            genres: string[];
            /** @description HDR format type */
            hdr_type?: string | null;
            /** @description Unique item identifier */
            id: string;
            /**
             * Format: int32
             * @description Index number (episode number, etc.)
             */
            index_number?: number | null;
            /** @description Type of item (movie, series, season, episode) */
            item_kind: string;
            /** @description Library this item belongs to */
            library_id: string;
            /** @description Item name/title */
            name: string;
            /** @description Content rating (PG, R, etc.) */
            official_rating?: string | null;
            /** @description Original title (if different from name) */
            original_title?: string | null;
            /** @description Plot summary */
            overview?: string | null;
            /** @description Parent item ID (for episodes, seasons, etc.) */
            parent_id?: string | null;
            /**
             * Format: int32
             * @description Parent index number (season number, etc.)
             */
            parent_index_number?: number | null;
            /** @description Premiere date */
            premiere_date?: string | null;
            /**
             * Format: int32
             * @description Year of production
             */
            production_year?: number | null;
            /** @description External provider IDs */
            provider_ids: components["schemas"]["ProviderIdsResponse"];
            /**
             * Format: int64
             * @description Runtime in ticks (100ns units)
             */
            runtime_ticks?: number | null;
            /** @description Sort name */
            sort_name?: string | null;
            /** @description Studios */
            studios: string[];
            /** @description Tagline */
            tagline?: string | null;
        };
        /** @description Paginated list of items. */
        ItemsListResponse: {
            /** @description Items in this page */
            items: components["schemas"]["ItemResponse"][];
            /**
             * Format: int32
             * @description Limit used
             */
            limit: number;
            /**
             * Format: int32
             * @description Offset used
             */
            offset: number;
            /**
             * Format: int32
             * @description Total number of items matching the filter
             */
            total_count: number;
        };
        /** @description Job information. */
        Job: {
            /** @description When processing completed */
            completed_at?: string | null;
            /** @description When the job was created */
            created_at: string;
            /** @description Current processing step */
            current_step?: string | null;
            /** @description Error message if failed */
            error?: string | null;
            /** @description File name */
            file_name: string;
            /** @description Path to the media file */
            file_path: string;
            /** @description Unique job identifier */
            id: string;
            /**
             * Format: float
             * @description Progress percentage (0-100)
             */
            progress: number;
            /** @description Name of the matched rule */
            rule_name?: string | null;
            /** @description Source of the job */
            source: components["schemas"]["JobSource"];
            /** @description When processing started */
            started_at?: string | null;
            /** @description Current job status */
            status: components["schemas"]["JobStatus"];
        };
        /** @description Source of a job. */
        JobSource: {
            /** @description Job submitted via webhook */
            Webhook: {
                arr_name: string;
                /** Format: int64 */
                item_id?: number | null;
            };
        } | {
            /** @description Job detected by file watcher */
            Watcher: {
                watch_path: string;
            };
        } | "Manual" | "Api";
        /** @description Processing statistics. */
        JobStats: {
            /**
             * Format: int64
             * @description Number of failed jobs
             */
            failed: number;
            /**
             * Format: int64
             * @description Number of successful jobs
             */
            successful: number;
            /**
             * Format: int64
             * @description Total bytes processed
             */
            total_bytes_processed: number;
            /**
             * Format: int64
             * @description Total number of processed jobs
             */
            total_processed: number;
        };
        /**
         * @description Job status.
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        /** @description Library information. */
        LibraryResponse: {
            /** @description When the library was created */
            created_at: string;
            /** @description Unique library identifier */
            id: string;
            /** @description Type of media in this library */
            media_type: string;
            /** @description Library name */
            name: string;
            /** @description Paths scanned for media files */
            paths: string[];
        };
        /** @description Conditions for matching media files. */
        MatchConditions: {
            /** @description Audio codecs to match */
            audio_codecs: string[];
            /** @description Video codecs to match */
            codecs: string[];
            /** @description Container formats to match */
            containers: string[];
            /** @description Dolby Vision profiles to match */
            dolby_vision_profiles: number[];
            /** @description HDR formats to match (sdr, hdr10, hdr10+, dolbyvision, hlg) */
            hdr_formats: string[];
            max_resolution?: null | components["schemas"]["Resolution"];
            min_resolution?: null | components["schemas"]["Resolution"];
        };
        /** @description Media file information. */
        MediaFileResponse: {
            /** @description Audio codec */
            audio_codec?: string | null;
            /** @description Container format */
            container: string;
            /**
             * Format: int64
             * @description Duration in ticks (100ns units)
             */
            duration_ticks?: number | null;
            /** @description Path to the file */
            file_path: string;
            /**
             * Format: int64
             * @description File size in bytes
             */
            file_size: number;
            /**
             * Format: int32
             * @description Video height in pixels
             */
            height?: number | null;
            /** @description Unique file identifier */
            id: string;
            /** @description Whether the file is HDR */
            is_hdr: boolean;
            /** @description Item this file belongs to */
            item_id: string;
            /** @description File role (primary, secondary, etc.) */
            role: string;
            /** @description Whether this file serves as universal fallback */
            serves_as_universal: boolean;
            /** @description Video codec */
            video_codec?: string | null;
            /**
             * Format: int32
             * @description Video width in pixels
             */
            width?: number | null;
        };
        /** @description External provider IDs. */
        ProviderIdsResponse: {
            /** @description IMDB ID */
            imdb?: string | null;
            /** @description TMDB ID */
            tmdb?: string | null;
            /** @description TVDB ID */
            tvdb?: string | null;
        };
        /** @description Video resolution. */
        Resolution: {
            /**
             * Format: int32
             * @description Height in pixels
             */
            height: number;
            /**
             * Format: int32
             * @description Width in pixels
             */
            width: number;
        };
        /** @description Processing rule. */
        Rule: {
            /** @description Actions to perform when matched */
            actions: components["schemas"]["Action"][];
            /** @description Whether the rule is enabled */
            enabled: boolean;
            /** @description Match conditions */
            match: components["schemas"]["MatchConditions"];
            /** @description Rule name */
            name: string;
            /**
             * Format: int32
             * @description Priority (higher = matched first)
             */
            priority: number;
        };
        /** @description Request to submit a new job. */
        SubmitJobRequest: {
            /** @description Path to the media file to process */
            file_path: string;
        };
        /** @description Response after submitting a job. */
        SubmitJobResponse: {
            /** @description Path to the submitted file */
            file_path: string;
            /**
             * Format: uuid
             * @description Unique job identifier
             */
            job_id: string;
        };
        /** @description Arr connection test result. */
        TestResult: {
            /** @description Error message if failed */
            error?: string | null;
            /** @description Whether the test succeeded */
            success: boolean;
        };
        /** @description External tool status. */
        ToolStatusResponse: {
            /** @description Whether the tool is available */
            available: boolean;
            /** @description Tool name */
            name: string;
            /** @description Path to the tool */
            path?: string | null;
            /** @description Tool version if available */
            version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_arrs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Arr integrations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArrStatus"][];
                };
            };
        };
    };
    test_arr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Arr integration name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"];
                };
            };
            /** @description Arr not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_history: {
        parameters: {
            query?: {
                /** @description Maximum number of results to return */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    list_items_handler: {
        parameters: {
            query?: {
                /** @description Filter by library ID */
                library_id?: string | null;
                /** @description Filter by parent item ID */
                parent_id?: string | null;
                /** @description Filter by item kinds (comma-separated) */
                item_kinds?: string | null;
                /** @description Search term */
                search?: string | null;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Sort field */
                sort_by?: string | null;
                /** @description Sort in descending order */
                sort_desc?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemsListResponse"];
                };
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Invalid item ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_children: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of child items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
            /** @description Invalid item ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_item_files: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of media files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFileResponse"][];
                };
            };
            /** @description Invalid item ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_similar_items: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of similar items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
            /** @description Invalid item ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                /** @description Filter by status (queued, running, completed, failed, cancelled) */
                status?: string | null;
                /** @description Maximum number of results to return */
                limit?: number | null;
                /** @description Number of results to skip */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    submit_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitJobRequest"];
            };
        };
        responses: {
            /** @description Job submitted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitJobResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job already exists for this file */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job requeued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Cannot retry this job */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_libraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of libraries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"][];
                };
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_library: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLibraryRequest"];
            };
        };
        responses: {
            /** @description Library created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_library: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Library ID */
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description Invalid library ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Library not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_library: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Library ID */
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid library ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Library not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_library_items: {
        parameters: {
            query?: {
                /** @description Filter by library ID */
                library_id?: string | null;
                /** @description Filter by parent item ID */
                parent_id?: string | null;
                /** @description Filter by item kinds (comma-separated) */
                item_kinds?: string | null;
                /** @description Search term */
                search?: string | null;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Sort field */
                sort_by?: string | null;
                /** @description Sort in descending order */
                sort_desc?: boolean;
            };
            header?: never;
            path: {
                /** @description Library ID */
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemsListResponse"];
                };
            };
            /** @description Invalid library ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_recent_items: {
        parameters: {
            query?: {
                /** @description Filter by library ID */
                library_id?: string | null;
                /** @description Filter by parent item ID */
                parent_id?: string | null;
                /** @description Filter by item kinds (comma-separated) */
                item_kinds?: string | null;
                /** @description Search term */
                search?: string | null;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Sort field */
                sort_by?: string | null;
                /** @description Sort in descending order */
                sort_desc?: boolean;
            };
            header?: never;
            path: {
                /** @description Library ID */
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of recent items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
            /** @description Invalid library ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scan_library: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Library ID */
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid library ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scan failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    get_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    search_items: {
        parameters: {
            query: {
                /** @description Search term */
                q: string;
                /** @description Maximum number of results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
            /** @description Database not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processing statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStats"];
                };
            };
        };
    };
    get_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool status list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolStatusResponse"][];
                };
            };
        };
    };
}
